### ISSUE TITLE
Replicate track linking 2 Layout

### ISSUE THREAD

**Issue by labodezao** [MitjaNemec/Kicad_action_plugins#110]
Hi Here, i have on my principal sheet and inside i have 2 hierarchical sheet that I duplicate (one called Trct.sch and Din.sch)

How I placed those 2 module on the PCB and I would like to replicate the tracks linking those 2 layouts. 

How can I do that ? Do I need to put that over anoter hieracical sheet ?

**Comment by MitjaNemec** [comment]
Sorry, but I'll need a bit more info. Can you pate the schematics hierarchy so that I'll have a clearer picture of your project.

Something like this:
![image](https://user-images.githubusercontent.com/18001294/100478424-74cd6e00-30eb-11eb-82f9-085f7332ada9.png)

**Comment by MitjaNemec** [comment]
closing due to lack of user input
