### ISSUE TITLE
After first run replication plugin displays error

### ISSUE THREAD

**Issue by denizzzka** [MitjaNemec/Kicad_action_plugins#116]
After first sucessful run replication plugin displays this error window:

![image](https://user-images.githubusercontent.com/974632/106402543-879e4f00-645c-11eb-8295-df0241997d65.png)

**Comment by denizzzka** [comment]
Probably, duplicates #63

**Comment by MitjaNemec** [comment]
What KiCad version did you run the plugin with?

**Comment by denizzzka** [comment]
From Debian Unstable, "5.1.9+dfsg1-1, release build"

**Comment by denizzzka** [comment]
When I save scheme to disk plugin works correctly.

**Comment by MitjaNemec** [comment]
Yeah, it is #63. It is somewhat difficult for me to check consistency between schematics and layout, so I've given up on producing better error message especially as I am getting my rest before migrating plugins to V6
