### ISSUE TITLE
Replicate layout pluign: can't find destination sheets

### ISSUE THREAD

**Issue by PFC123456** [MitjaNemec/Kicad_action_plugins#132]
Hi, 
I try to run Replicate layout plugin in Kicad version (5.1.5)-3.
I tried Kicad (5.1.5)-3 and (5.1.9)-1, but the problem still exists.

![image](https://user-images.githubusercontent.com/85484690/121007011-2567a900-c7c4-11eb-889c-d4e119dd0a64.png)

![image](https://user-images.githubusercontent.com/85484690/121016369-a461df00-c7ce-11eb-8c5e-737d831ab6aa.png)

I built 4 simple circuits. In pcbnew, I selected a part (C1) from source section, run Replicate layout plugin, and encounter the problem:
it shows only source hierarchy level file, but there's no destination sheet, even though I clicked or double clicked "file60BDF436.sch"

After I clicked the "Ok" button, there's no any action happend.

Did anyone encounter this problem, too?
How to solve it?

**Comment by MitjaNemec** [comment]
Did you save the schematics before running the plugin?

**Comment by PFC123456** [comment]
> Did you save the schematics before running the plugin?

Yes, I did save the schematic before running the plugin.

**Comment by PFC123456** [comment]
Here's the log file.

[replicate_layout.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/6608070/replicate_layout.log)

**Comment by MitjaNemec** [comment]
Hmmm,

1. can you deselect and select the item in source hierarchy level. I've had some changes here and I don't recall testing it with such a simple project.
2. Would you mind sharing the project?
3. Would you mind updating your KiCad installation? I am always testing the plugin against only the latest KiCad version

**Comment by PFC123456** [comment]
> Hmmm,
> 
> 1. can you deselect and select the item in source hierarchy level. I've had some changes here and I don't recall testing it with such a simple project.
> 2. Would you mind sharing the project?
> 3. Would you mind updating your KiCad installation? I am always testing the plugin against only the latest KiCad version

Thanks for your reply. Here's my project file.
[test_05.zip](https://github.com/MitjaNemec/Kicad_action_plugins/files/6608685/test_05.zip)

I have tried running place footprints plugin in Kicad (5.1.5)-3 and (5.1.9)-1, it work well.
But in both Kicad (5.1.5)-3 and (5.1.9)-1, Replicate layout pluign doesn't work.

**Comment by MitjaNemec** [comment]
@PFC123456 , your issue with replicate layout plugin should be solved now

**Comment by PFC123456** [comment]
> @PFC123456 , your issue with replicate layout plugin should be solved now

No, the issue still exists. Do you know how to solve it?

**Comment by MitjaNemec** [comment]
You did update the plugin with the latest version? If you did, can you attach the latest `replicate_layout.log` file that should be in your project folder.
I could reproduce the issue with your project, and I've implemented a solution which worked on my side. It could be that the issue is also OS specific (I am on Kubuntu 20.04)

**Comment by PFC123456** [comment]
> You did update the plugin with the latest version? If you did, can you attach the latest `replicate_layout.log` file that should be in your project folder.
> I could reproduce the issue with your project, and I've implemented a solution which worked on my side. It could be that the issue is also OS specific (I am on Kubuntu 20.04)

I update the plugin with the last version, and the issue is solved now (on Kicad (5.1.5)-3 / Windows 10)

Here's the latest log file. 
[replicate_layout.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/6609635/replicate_layout.log)

I really appreciate your patience, reply, and support!

**Comment by MitjaNemec** [comment]
No worries, thanks for reporting it
