### ISSUE TITLE
Create a 'update mode' on `replicate_layout`

### ISSUE THREAD

**Issue by hildogjr** [MitjaNemec/Kicad_action_plugins#17]
`replicate_layout` already have the XY align and the circular align, so create a 'update mode' on `replicate_layout` to just update the already created replicated layouts. Use the selected component in the base layout as offset/origin in all the other ones; so the position of these components will not change in Pcbnew.
This may be useful to update the various replicated layout after integrated in the big layout.

**Comment by hildogjr** [comment]
Exactly.
About the step 4. Because we usually select one component of the pivot (master) to use the plugin, it could be use this orientation (XY and angle) to others.
This should be useful when the different replicated layouts are already placed on the PDB and I just want to make same track/footprint update that will affect all them.

**Comment by MitjaNemec** [comment]
Partial fixed pushed right now, but I don't know if supporting circular layout is even possible without additional input from the user

**Comment by hildogjr** [comment]
Closing this as fixed by the function "Grab offset from layout".
