### ISSUE TITLE
Replicate parts doen't take account REF width

### ISSUE THREAD

**Issue by hildogjr** [MitjaNemec/Kicad_action_plugins#19]
Replicate parts doen't take account REF width / height / tickness.

To reproduce:
1) Do the placement and tracks of one channel;
2) Adjust the Reference Silk, change it width / height / tickness;
3) Use the replicate plugin;
4) See that the new parts follow the standard library / Pcbnew silk configuration.

Propose:
Add a check box on the plugin: "replicate the silk configurations".

**Comment by MitjaNemec** [comment]
Thanks for spotting this. This will be a default behavior, as I don't see a reason to clutter the GUI.
