### ISSUE TITLE
Replicate layout in matrix format

### ISSUE THREAD

**Issue by hildogjr** [MitjaNemec/Kicad_action_plugins#20]
The replicate plugin have the X & Y offset but just do linear and diagonal placement. Would be nice a matrix placement.

**Comment by MitjaNemec** [comment]
Yup. but this is going to be low on my list of priorities, as I suspect it will require refactoring of the existent code.

**Comment by capaulson** [comment]
+1 for adding this as a feature

**Comment by MitjaNemec** [comment]
I am closing it, as the feature is implemented with Place footprints plugin. If you have an issue how the feature is implemented, open a new issue please.

**Comment by capaulson** [comment]
Woah, cool! Thanks @MitjaNemec!!!
