### ISSUE TITLE
Swap pins exception

### ISSUE THREAD

**Issue by robert128** [MitjaNemec/Kicad_action_plugins#26]
Hello Mitja,

Unfortunately, I'm getting an exception when trying to run your indispensable swap pins plugin while using Kicad version 5.0.1-44.  I've looked at the log and don't see anything significant.  Here is a screenshot of the exception:

![image](https://user-images.githubusercontent.com/12902944/49110425-50133700-f242-11e8-8dd6-cb810748ac6d.png)

Thanks

**Comment by MitjaNemec** [comment]
I think I've found it. There was a change in the cache.lib internal format sometime between V5 nightlies and V5.0.1. I've added a fix for it, so it should be working. Any feedback is appreciated

**Comment by robert128** [comment]
It's working now.  Thank you!!
