### ISSUE TITLE
net2net: distance always reported in mm

### ISSUE THREAD

**Issue by evanshultz** [MitjaNemec/Kicad_action_plugins#33]
Even if the Pcbnew units are set to IN (Imperial), the dialog shows mm.

**Comment by MitjaNemec** [comment]
Yes, I'll have to used freshly exposed `GetUserUnits` method and take this into account in most of my plugind (net2net, pad2pad, place_footprints, ...)

**Comment by MitjaNemec** [comment]
This was fiexd in d2946267, closing the issue
