### ISSUE TITLE
net2net: Support selecting elements other than pads

### ISSUE THREAD

**Issue by evanshultz** [MitjaNemec/Kicad_action_plugins#34]
Running the script fails if two and only two pads are not selected.

Since this is a _net_ tool, allow selection of vias, tracks, and other elements that are part of a net. Or any combination of those elements. You mentioned at https://github.com/MitjaNemec/Kicad_action_plugins/issues/29 that it is not going to work for zones so I didn't list them.

**Comment by MitjaNemec** [comment]
Yes, this makes sense. Will update shortly.

**Comment by MitjaNemec** [comment]
Thanks for the feedback
