### ISSUE TITLE
Fatal error when executing place footprints in matrix

### ISSUE THREAD

**Issue by nxxsr** [MitjaNemec/Kicad_action_plugins#61]
08-20 08:09:23 place_footprints.action_place_footprints 687:Fatal error when executing place footprints
Traceback (most recent call last):
  File "C:\Users\xiaoxu.niu.WONDERLAN\AppData\Roaming\kicad\scripting\plugins/place_footprints/action_place_footprints.py", line 682, in Run
    placer.place_matrix(sorted_modules, step_x, step_y, nr_columns)
TypeError: place_matrix() takes exactly 6 arguments (5 given)

**Comment by MitjaNemec** [comment]
Sorry about it, although I test the backend regularly, the UI is left for manual testing, and I forgot to test all cases. Should be fixed now

**Comment by nxxsr** [comment]
Thank you. Appreciate the plugin. Huge time saver!
