### ISSUE TITLE
place footprints only select part of available footprints

### ISSUE THREAD

**Issue by nxxsr** [MitjaNemec/Kicad_action_plugins#62]
only part of the footprints are selected by reference. None of the parts are selected by Hierarchy level.

![Capture](https://user-images.githubusercontent.com/19275883/64267303-2b03d100-cf04-11e9-9dd1-7ba2fdb2e19e.PNG)

![image](https://user-images.githubusercontent.com/19275883/64267417-5be40600-cf04-11e9-83d6-88ee54fc9cb1.png)

**Comment by MitjaNemec** [comment]
First, thanks for reporting. I really appreciate thorough testing that only real life cases can provide. Now if you can, then please send me the `place_footprints.log` file so I can start locating the bug. I might ask for some additional info, but the .log file should be a good start

**Comment by MitjaNemec** [comment]
@nxxsr can you attach the log file please?

**Comment by MitjaNemec** [comment]
Select by reference should be working now, for select by hierarchy sheet I'll need the .log file
