### ISSUE TITLE
KiCad get frozen after replication

### ISSUE THREAD

**Issue by hildogjr** [MitjaNemec/Kicad_action_plugins#67]
Using the commit 5c559b2dc219a3384b770b6c62f375a68dbda5e5, KiCad get frozen but the replication worked just fine (despise the need to restart KiCad).

I don't known if is a plugin or Pcbnew issue. Follow the log, if useful.
[replicate_layout.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/3635805/replicate_layout.log)

**Comment by MitjaNemec** [comment]
Which KiCad version did you run the plugin in?

**Comment by hildogjr** [comment]
It was last week Nightly version. I tested on today's Nightly and it is OK.
Version: 5.99.0-unknown-bba949c~86~ubuntu16.04.1, release build
