### ISSUE TITLE
Allow alternative angle

### ISSUE THREAD

**Issue by a7hybnj2** [MitjaNemec/Kicad_action_plugins#72]
Allow for circular layout as illustrated in attached screenshot.
<img width="1054" alt="Screen Shot 2019-12-23 at 23 34 43" src="https://user-images.githubusercontent.com/36831279/71410040-cb941300-2611-11ea-9500-06146b785360.png">

**Comment by MitjaNemec** [comment]
This is already doable.

The footprint that you select when calling the plugin has to be oriented vertically, as the selected serves as an anchor and the plugin and goes  clockwise/counterclokwise (increasing/decereasing references/sheet numbers)

Before
![image](https://user-images.githubusercontent.com/18001294/71410310-0c594f80-2645-11ea-842d-79d76132aede.png)

After
![image](https://user-images.githubusercontent.com/18001294/71410318-124f3080-2645-11ea-8bf4-0c488610bf08.png)

**Comment by a7hybnj2** [comment]
@MitjaNemec Yep, I had just tried this. I came back here to let you know I figured it out and you beat me too it!

Seems awesome and exactly what I wanted. Thanks!
