### ISSUE TITLE
error while loading net2net into kicad

### ISSUE THREAD

**Issue by T0jan** [MitjaNemec/Kicad_action_plugins#76]
hi again,

after I did an update of my local version to the latest commit, Kicad fails to import net2net:

[net2net_min_distance_error.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/4026066/net2net_min_distance_error.log)

the rest runs smoothly

best regards.

**Comment by MitjaNemec** [comment]
Thanks for reporting it. It'll take a couple of days before I get on it.
