### ISSUE TITLE
Plz refer to eeschema in introduction Readme.md

### ISSUE THREAD

**Issue by kenneth558** [MitjaNemec/Kicad_action_plugins#77]
Kicad_action_plugins:
It would be helpful to those of us who aren't sure if pcbnew has hierarchical sheets or not if you would tag on to the README.md sentence "The replication is based upon hierarchical sheets. " an additional two words like so: "The replication is based upon hierarchical sheets in eeschema."  Thank you!

**Comment by MitjaNemec** [comment]
I can only agree that the documentation of the plugins should be expanded. It is on my to do list, but recently I have a hard time finding time for plugins support and development.

**Comment by MitjaNemec** [comment]
Thanks for reporting it. User feedback can make the plugins and it's documentation better and it is much appreciated.
