### ISSUE TITLE
Crash while replicate layout

### ISSUE THREAD

**Issue by xDraconix** [MitjaNemec/Kicad_action_plugins#79]
KiCAD Version: (5.1.5)-3, release build

Ive got following error while replicate:

![replicate_error](https://user-images.githubusercontent.com/28046753/74588426-9f3ab880-4ffc-11ea-9597-4b361cb16b0f.png)

here are the recent log file:

[replicate_layout.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/4208489/replicate_layout.log)

**Comment by Bratwurstdealer** [comment]
I'm having the same problem with version (5.0.1)-3, release build running on windows 10.

[replicate_layout.log](https://github.com/MitjaNemec/Kicad_action_plugins/files/4208505/replicate_layout.log)

**Comment by xDraconix** [comment]
Sorry, that was my fault! I have delete one compoment after routing them. After that, the footprint still exist at pcbnew, but in the newly importet second hierarchical sheet, they cant route to the non existing footprint.

Closed for my issue.

**Comment by MitjaNemec** [comment]
@Bratwurstdealer the error window within the KiCad is the same for any error caught. Looking at the .log file, I can see that you have a different issue. It might be that 5.0.1 does not have the SetKeepUpright method implemented.

Can you confirm this by opening the python console within pcbnew and enter
```
import pcbnew
repr(pcbnew.TEXTE_MODULE.SetKeepUpright)
```
you should get `'<unbound method TEXTE_MODULE.SetKeepUpright>'` as an answer.

if you get something like `AttributeError: type object 'TEXTE_MODULE' has no attribute 'SetKeepUpright'` then you have two options:
1. either you upgrade KiCad to 5.1. branch
2. use [older revision](https://github.com/MitjaNemec/Kicad_action_plugins/commits/master) of the plugin (the latest commit that should still work is d3655a)

**Comment by MitjaNemec** [comment]
@xDraconix Thanks for letting me know. I'll still look int it as it would be nice if the plugin reported more specific message

**Comment by Bratwurstdealer** [comment]
Thanks for the response @MitjaNemec!
The problem was the outdated Kicad version I used. I updated my Kicad and now it works fine.
