### ISSUE TITLE
All plugins in a single folder

### ISSUE THREAD

**Issue by iperkeno** [MitjaNemec/Kicad_action_plugins#89]
Thanks for the great job!!!!!!
I added `__ini__.py` in main folder:
```
from . import archive_project
from . import delete_selected
from . import length_stats
from . import net2net_min_distance
from . import pad2pad_track_distance
from . import place_footprints
from . import replicate_layout
from . import save_restore_layout
from . import screenshots
from . import swap_pins
from . import swap_units
```
and pcbnew loads correctly all the plugins
I find more practical to have all plugins from one author in the same folder.
Thank you again

**Comment by MitjaNemec** [comment]
This is a neat idea. Thanks for sharing. But as users might put plugins differently, I'll not implement this.
